audio_processing:
  device: cuda
  diarization:
    clustering_method: agglomerative
    enable_overlap_detection: false
    max_segment_gap: 0.15
    max_speakers: 4
    min_segment_duration: 1.5
    min_speakers: 2
    overlap_threshold: 0.25
  diarization_model: pyannote/speaker-diarization-3.1
  language: auto
  model: large-v3
  preprocessing:
    apply_bandpass_filter: true
    filter_high_hz: 3400
    filter_low_hz: 300
    normalize_audio: true
  segment_duration: 600
  segment_overlap: 15
  skip_diarization: true
  speaker_bank:
    backend: faiss
    dim: 128
  two_pass_processing: false
  use_faster_whisper: false
  use_whisper: false
  use_whisperx: true
  vad:
    cross_validate: true
    min_silence_duration_ms: 300
    min_speech_duration_ms: 250
    speech_pad_ms: 50
    threshold: 0.2
    window_size_samples: 512
  whisperx:
    batch_size: 8
    compute_type: float16
    language: auto
device: cuda
entity_detection:
  batch_size: 8
  box_threshold: 0.3
  detector: grounding_sam
  device: cuda
  grounding_dino_checkpoint_path: models/grounding_sam/groundingdino_swint_ogc.pth
  grounding_dino_config_path: models/grounding_sam/GroundingDINO_SwinT_OGC.py
  min_confidence: 0.3
  process_keyframes_in_batches: true
  prompt: person . car . bus . truck . animal . object . building . tree . sign .
    food . clothing . face . hand . chair . table . bottle . cup . book . phone .
    laptop . tv . plant
  sam_checkpoint_path: models/grounding_sam/sam_vit_h_4b8939.pth
  sam_model_type: vit_h
  text_threshold: 0.25
  use_face_detection: true
  use_ocr: true
gemini_vision:
  api_key: AIzaSyBU4Y80iuDXXITH2HHLM0Cv6Gs4vs-9ucM
  max_tokens: 1024
  scene_analysis_fields:
  - setting
  - emotions
  - action
  - characters
  - dialogue
  - cinematography
  - significance
  - technical_notes
  structured_output: true
  temperature: 0.5
  top_k: 40
  top_p: 0.8
keyframe_extraction:
  aggressive_sampling_threshold: 10000
  batch_size: 32
  device: cuda
  fallback_to_uniform: true
  frames_per_scene: 5
  max_frames_per_scene: 8
  max_frames_to_extract: 64
  method: content_based
  min_frames_per_scene: 3
  use_minibatch_kmeans: true
log_level: INFO
memory_optimization:
  batch_size_frames: 32
  cleanup_interval: 500
  enabled: true
  frame_sampling_rate: 2
  max_embeddings_per_batch: 500
  max_frames_in_memory: 2000
  use_dynamic_batch_size: true
  use_float16_precision: true
output_dir: output
parallel_processing:
  cache_dir: .cache
  cache_ttl: 86400
  enabled: true
  max_workers: 4
  use_result_cache: true
scene_detection:
  batch_size: 32
  clip_model: ViT-L-14
  clip_pretrained: openai
  combine_scenes: true
  device: cuda
  max_scene_duration: 300.0
  max_temporal_gap: 2.0
  min_scene_duration: 20.0
  min_scene_length: 10.0
  min_viable_scene_duration: 15.0
  setting_similarity_threshold: 0.75
  similarity_window: 10
  target_scene_duration: 60.0
  threshold: 0.65
  use_windowed_processing: true
  window_duration: 600
  window_overlap: 30
video_processing:
  fps: 25
  max_scenes: 100
  resolution:
  - 1920
  - 1080
  target_scene_duration: 60.0
